- port_limit    : 2
  version       : 2
  low_end       : true
  interfaces    : ["veth0", "veth3"]
  port_info     :
                 - ip         : 1.1.1.1
                   default_gw : 2.2.2.2
                 - ip         : 2.2.2.2
                   default_gw : 1.1.1.1
